export const skillsContent = {
  es: {
    title: "Habilidades técnicas",
    description: "Mi stack tecnológico y herramientas que utilizo para crear experiencias digitales excepcionales.",
    categories: [
      {
        name: "Desarrollo",
        key: "development",
        description: "Tecnologías que uso para construir interfaces modernas y responsivas.",
      },
      {
        name: "Diseño y Multimedia",
        key: "design",
        description: "Herramientas para crear experiencias visuales impactantes.",
      },
      {
        name: "Herramientas y Metodologías",
        key: "tools",
        description: "Recursos que utilizo para optimizar mi flujo de trabajo.",
      },
    ],
    skills: {
      development: [
        {
          name: "JavaScript",
          icon: "/icons/javascript.svg",
          level: "Avanzado",
          color: "#F7DF1E",
          description: "ES6+, Promesas, Async/Await, DOM",
        },
        {
          name: "Bootstrap",
          icon: "/icons/bootstrap.svg",
          level: "Avanzado",
          color: "#7952B3",
          description: "Grid System, Componentes, Utilidades",
        },
        {
          name: "TypeScript",
          icon: "/icons/typescript.svg",
          level: "Intermedio-Avanzado",
          color: "#3178C6",
          description: "Tipos, Interfaces, Genéricos",
        },
        {
          name: "React",
          icon: "/icons/react.svg",
          level: "Avanzado",
          color: "#61DAFB",
          description: "Hooks, Context, Suspense",
        },
        {
          name: "Next.js",
          icon: "/icons/nextjs.svg",
          level: "Intermedio-Avanzado",
          color: "#444444",
          description: "App Router, Server Components, API Routes",
        },
        {
          name: "HTML5",
          icon: "/icons/html5.svg",
          level: "Avanzado",
          color: "#E34F26",
          description: "Semántica, Accesibilidad, SEO",
        },
        {
          name: "CSS3",
          icon: "/icons/css3.svg",
          level: "Avanzado",
          color: "#1572B6",
          description: "Flexbox, Grid, Animaciones",
        },
        {
          name: "Tailwind CSS",
          icon: "/icons/tailwindcss.svg",
          level: "Avanzado",
          color: "#06B6D4",
          description: "Configuración, Plugins, JIT",
        },
        {
          name: "Redux",
          icon: "/icons/redux.svg",
          level: "Intermedio",
          color: "#764ABC",
          description: "Redux Toolkit, Thunks",
        },
        {
          name: "Node.js",
          icon: "/icons/nodejs.svg",
          level: "Intermedio",
          color: "#339933",
          description: "Express, MongoDB, REST APIs",
        },
        {
          name: "Python",
          icon: "/icons/python.svg",
          level: "Intermedio",
          color: "#3572A5",
          description: "Flask, Django, REST APIs",
        },
        {
          name: "API Development",
          icon: "/icons/api.svg",
          level: "Intermedio-Avanzado",
          color: "#6DB33F",
          description: "REST, Autenticación, Documentación",  
        },
      ],
      design: [
        {
          name: "Figma",
          icon: "/icons/figma.svg",
          level: "Intermedio-Avanzado",
          color: "#F24E1E",
          description: "Prototipos, Componentes, Auto Layout",
        },
        {
          name: "Adobe Photoshop",
          icon: "/icons/photoshop.svg",
          level: "Avanzado",
          color: "#31A8FF",
          description: "Edición, Composición, Retoque",
        },
        {
          name: "Adobe Premiere",
          icon: "/icons/premiere.svg",
          level: "Intermedio-Avanzado",
          color: "#9999FF",
          description: "Edición, Color, Audio",
        },
        {
          name: "Adobe After Effects",
          icon: "/icons/aftereffects.svg",
          level: "Intermedio",
          color: "#9999FF",
          description: "Animación, Composición, VFX",
        },
        {
          name: "Canva",
          icon: "/icons/canva.svg",
          level: "Avanzado",
          color: "#00C4CC",
          description: "Diseño rápido, Plantillas, Colaboración",
        },
        {
          name: "CapCut",
          icon: "/icons/capcut.svg",
          level: "Intermedio-Avanzado",
          color: "#9999FF",
          description: "Edición de videos, Efectos, Transiciones",
        },
        {
          name: "UI/UX Design",
          icon: "/icons/ux.svg",
          level: "Intermedio-Avanzado",
          color: "#FF5722",
          description: "Wireframes, Usabilidad, Investigación",
        },
      ],
      tools: [
        {
          name: "Git & GitHub",
          icon: "/icons/github.svg",
          level: "Avanzado",
          color: "#666666",
          description: "Branching, PR, CI/CD",
        },
        {
          name: "VS Code",
          icon: "/icons/vscode.svg",
          level: "Avanzado",
          color: "#007ACC",
          description: "Extensiones, Snippets, Depuración",
        },
        {
          name: "WordPress",
          icon: "/icons/wordpress.svg",
          level: "Intermedio-Avanzado",
          color: "#21759B",
          description: "Temas, Plugins, Gutenberg",
        },
        {
          name: "Scrum/Kanban",
          icon: "/icons/agile.svg",
          level: "Intermedio",
          color: "#6DB33F",
          description: "Sprints, Historias, Retrospectivas",
        },
        {
          name: "Jira",
          icon: "/icons/jira.svg",
          level: "Intermedio",
          color: "#0052CC",
          description: "Tickets, Workflows, Reportes",
        },
        {
          name: "Notion",
          icon: "/icons/notion.svg",
          level: "Avanzado",
          color: "#555555",
          description: "Bases de datos, Wikis, Gestión de proyectos",
        },
      ],
    },
  },
  en: {
    title: "Technical Skills",
    description: "My technology stack and tools I use to create exceptional digital experiences.",
    categories: [
      {
        name: "Development",
        key: "development",
        description: "Technologies I use to build modern and responsive interfaces.",
      },
      {
        name: "Design & Multimedia",
        key: "design",
        description: "Tools for creating impactful visual experiences.",
      },
      {
        name: "Tools & Methodologies",
        key: "tools",
        description: "Resources I use to optimize my workflow.",
      },
    ],
    skills: {
      development: [
        {
          name: "JavaScript",
          icon: "/icons/javascript.svg",
          level: "Advanced",
          color: "#F7DF1E",
          description: "ES6+, Promises, Async/Await, DOM",
        },
        {
          name: "Bootstrap",
          icon: "/icons/bootstrap.svg",
          level: "Advanced",
          color: "#7952B3",
          description: "Grid System, Components, Utilities",
        },
        {
          name: "TypeScript",
          icon: "/icons/typescript.svg",
          level: "Intermediate-Advanced",
          color: "#3178C6",
          description: "Types, Interfaces, Generics",
        },
        {
          name: "React",
          icon: "/icons/react.svg",
          level: "Advanced",
          color: "#61DAFB",
          description: "Hooks, Context, Suspense",
        },
        {
          name: "Next.js",
          icon: "/icons/nextjs.svg",
          level: "Intermediate-Advanced",
          color: "#444444",
          description: "App Router, Server Components, API Routes",
        },
        {
          name: "HTML5",
          icon: "/icons/html5.svg",
          level: "Advanced",
          color: "#E34F26",
          description: "Semantics, Accessibility, SEO",
        },
        {
          name: "CSS3",
          icon: "/icons/css3.svg",
          level: "Advanced",
          color: "#1572B6",
          description: "Flexbox, Grid, Animations",
        },
        {
          name: "Tailwind CSS",
          icon: "/icons/tailwindcss.svg",
          level: "Advanced",
          color: "#06B6D4",
          description: "Configuration, Plugins, JIT",
        },
        {
          name: "Redux",
          icon: "/icons/redux.svg",
          level: "Intermediate",
          color: "#764ABC",
          description: "Redux Toolkit, Thunks",
        },
        {
          name: "Node.js",
          icon: "/icons/nodejs.svg",
          level: "Intermediate",
          color: "#339933",
          description: "Express, MongoDB, REST APIs",
        },
        {
          name: "Python",
          icon: "/icons/python.svg",
          level: "Intermediate",
          color: "#3572A5",
          description: "Flask, Django, REST APIs",
        },
        {
          name: "API Development",
          icon: "/icons/api.svg",
          level: "Intermediate-Advanced",
          color: "#6DB33F",
          description: "REST, Authentication, Documentation",  
        },
      ],
      design: [
        {
          name: "Figma",
          icon: "/icons/figma.svg",
          level: "Intermediate-Advanced",
          color: "#F24E1E",
          description: "Prototypes, Components, Auto Layout",
        },
        {
          name: "Adobe Photoshop",
          icon: "/icons/photoshop.svg",
          level: "Advanced",
          color: "#31A8FF",
          description: "Editing, Composition, Retouching",
        },
        {
          name: "Adobe Premiere",
          icon: "/icons/premiere.svg",
          level: "Intermediate-Advanced",
          color: "#9999FF",
          description: "Editing, Color, Audio",
        },
        {
          name: "Adobe After Effects",
          icon: "/icons/aftereffects.svg",
          level: "Intermediate",
          color: "#9999FF",
          description: "Animation, Composition, VFX",
        },
        {
          name: "Canva",
          icon: "/icons/canva.svg",
          level: "Advanced",
          color: "#00C4CC",
          description: "Quick design, Templates, Collaboration",
        },
        {
          name: "CapCut",
          icon: "/icons/capcut.svg",
          level: "Intermediate-Advanced",
          color: "#9999FF",
          description: "Video editing, Effects, Transitions",
        },
        {
          name: "UI/UX Design",
          icon: "/icons/ux.svg",
          level: "Intermediate-Advanced",
          color: "#FF5722",
          description: "Wireframes, Usability, Research",
        },
      ],
      tools: [
        {
          name: "Git & GitHub",
          icon: "/icons/github.svg",
          level: "Advanced",
          color: "#666666",
          description: "Branching, PR, CI/CD",
        },
        {
          name: "VS Code",
          icon: "/icons/vscode.svg",
          level: "Advanced",
          color: "#007ACC",
          description: "Extensions, Snippets, Debugging",
        },
        {
          name: "WordPress",
          icon: "/icons/wordpress.svg",
          level: "Intermediate-Advanced",
          color: "#21759B",
          description: "Themes, Plugins, Gutenberg",
        },
        {
          name: "Scrum/Kanban",
          icon: "/icons/agile.svg",
          level: "Intermediate",
          color: "#6DB33F",
          description: "Sprints, Stories, Retrospectives",
        },
        {
          name: "Jira",
          icon: "/icons/jira.svg",
          level: "Intermediate",
          color: "#0052CC",
          description: "Tickets, Workflows, Reports",
        },
        {
          name: "Notion",
          icon: "/icons/notion.svg",
          level: "Advanced",
          color: "#555555",
          description: "Databases, Wikis, Project management",
        },
      ],
    },
  },
} 